version: 2

jobs:
  build:
    docker:
      - image: circleci/elixir:latest
    environment:
      MIX_ENV: test
    steps:
      - checkout
      - run: docker-compose up -d
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run: mix format --check-formatted
      - run: mix coveralls.circle
