name: CI

on: [push, pull-request]

jobs:
  test:
    runs-on: ubuntu:latest

    steps:
      - name: Install Elixir
        run: |
          wget https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb && sudo dpkg -i erlang-solutions_1.0_all.deb
          apt update
          apt install esl-erlang
          apt install elixir
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - name: Run Tests
        run: mix test

    services:
      ejabberd:
        image: rroemhild/ejabberd
        ports:
          - 5222:5222
          - 5269:5269
          - 5280:5280
        env:
          XMPP_DOMAIN: localhost
          EJABBERD_SKIP_MODULES_UPDATE: true
        options: --name ejabberd
