name: CI

on: [push, pull-request]

jobs:
  test:
    runs-on: ubuntu:latest

    services:
      ejabberd:
        image: rroemhild/ejabberd
        ports:
          - 5222:5222
          - 5269:5269
          - 5280:5280
        env:
          XMPP_DOMAIN: localhost
          EJABBERD_SKIP_MODULES_UPDATE: true
        options: --name ejabberd

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-elixir@v1
        with:
          otp-version: 22.0
          elixir-version: 1.9.1
      - run: mix deps.get
      - run: mix test
